
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SESI_SENAI
 */
public class VinteUm extends javax.swing.JFrame {
    
    int random_int1;
    int random_int2;
    int random_int3;
    int soma;
    int win = 0;

    

    /**
     * Creates new form VinteUm
     */
    public VinteUm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Carta = new javax.swing.JLabel();
        somaa = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Vitoria = new javax.swing.JLabel();
        pikapika = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Comprar cartas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Carta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Carta.setText("Cartas:");

        somaa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        somaa.setText("Soma das cartas:");

        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Vitoria.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Vitoria.setText("Vitórias: 0");

        pikapika.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pikapika.setText("Pikachu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(somaa)
                                    .addComponent(Carta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(Vitoria)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pikapika)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Vitoria)
                .addGap(74, 74, 74)
                .addComponent(Carta)
                .addGap(40, 40, 40)
                .addComponent(pikapika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(somaa)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        
    Random();  
    Carta.setText("Cartas: " + random_int1 +", "+random_int2+" e "+random_int3);
    somaa.setText("Soma: "+soma);
    if(soma < 21){
        int resposta = JOptionPane.showConfirmDialog(null, "Você possui " +soma + ", deseja comprar mais uma carta?");
        if(resposta == 0){
            Random1();
        }else if(resposta == 1){
                       JOptionPane.showMessageDialog(null, "Então sua pontuação final será " + soma);
               somaa.setText("Soma: "+ soma);
        }
    }

    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VinteUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VinteUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VinteUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VinteUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VinteUm().setVisible(true);
            }
        });
    }
    public void Random(){
      int min = 1;
      int max = 10;
        
      random_int1 = (int)Math.floor(Math.random()*(max-min+1)+min);
      random_int2 = (int)Math.floor(Math.random()*(max-min+1)+min);
      random_int3 = (int)Math.floor(Math.random()*(max-min+1)+min);

      JOptionPane.showMessageDialog(null,"Suas cartas são: "+ random_int1+", "+random_int2+" e "+random_int3);    
      
      soma = random_int1+random_int2+random_int3;
      if(soma>21){
          JOptionPane.showMessageDialog(null, "Infelizmente você perdeu");

      }if(soma < 21){
          JOptionPane.showMessageDialog(null, "Bela mão.");
      }if(soma == 21){
          JOptionPane.showMessageDialog(null, "Parabéns, você ganhou");
          
          win = win + 1;
                    Vitoria.setText("Vitórias: "+ win);                
      }
    
    }
    
    public void Random1(){
      int min = 1;
      int max = 10;
      int cartaa;
      int cartaa1;
      int resultata;
        
      cartaa = (int)Math.floor(Math.random()*(max-min+1)+min);
      if((soma + cartaa) == 21){
          JOptionPane.showMessageDialog(null, "Parabéns, você ganhou");

          win = win + 1;
              somaa.setText("Soma: "+soma);

          Vitoria.setText("Vitórias: "+ win);
          
          

      }
      if((soma + cartaa) > 21){
          JOptionPane.showMessageDialog(null, "Infelizmente você perdeu");

              somaa.setText("Soma: "+soma);

      }
      if((soma + cartaa) < 21){
          do{
              
          resultata = JOptionPane.showConfirmDialog(null, "Você tem "+ (soma+cartaa) +", deseja comprar mais uma?");
          if(resultata == 0){
          cartaa1 = (int)Math.floor(Math.random()*(max-min+1)+min);
          soma = soma + cartaa1;
          somaa.setText("Soma: "+soma);

          if(soma == 21){
          JOptionPane.showMessageDialog(null, "Parabéns, você ganhou");

                                        
          win = win + 1;
              somaa.setText("Soma: "+soma);

          Vitoria.setText("Vitórias: "+ win);
          
          }else if(soma > 21){
                  soma = soma + cartaa1;
                  somaa.setText("Soma: "+soma);

          JOptionPane.showMessageDialog(null, "Infelizmente você perdeu");

              
          }   
              
          }else if(resultata == 1){
           JOptionPane.showMessageDialog(null, "Então sua pontuação final será " + soma);
               somaa.setText("Soma: "+soma);

                  }                            
      } 
          while(soma < 21 && resultata == 0);                
    }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carta;
    private javax.swing.JLabel Vitoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel pikapika;
    private javax.swing.JLabel somaa;
    // End of variables declaration//GEN-END:variables
}
